{
 "title": "Pizza Tracker",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Pizza's Ordered",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "pizza_counter_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pizza Duration Sum",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    { "expr": "pizza_duration_sum", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Successfull Pizzas",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    { "operation": "GET /pizza", "service": "spring-boot-demo", "tags": "http.response.status_code=200" }
   ]
  },
  {
   "title": "Pizza Fails",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    { "operation": "GET /pizza", "service": "spring-boot-demo", "tags": "error=true" }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "{service_name=`spring-boot-demo`} | json | logfmt | drop __error__, __error_details__"
    }
   ]
  }
 ]
}